POST http://localhost:8080/products
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Sony Bravia X3",
  "description": "Sony TV",
  "price": 1699,
  "stock": 50,
  "categoryId": 2
}