POST http://localhost:8080/products
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "iPhone 17",
  "description": "Apple iPhone 17",
  "price": 1099,
  "stock": 200,
  "categoryId": 1
}